apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: custom-label
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  containers:
    - name: jnlp
      image: 'jenkins/inbound-agent:4.13.2-1-jdk11'
      imagePullPolicy: Always
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
    - name: java-container
      image: 'devblogs1/java-agent:1.0'
      imagePullPolicy: Always
      command:
        - cat
      tty: true
      env:
        - name: CUSTOM_ENV_VAR
          value: 'custom-value'
        - name: DOCKER_HOST
          value: "tcp://192.168.1.21:2375"