INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Clarence', 'Ho', '1980-07-30');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Scott', 'Tiger', '1990-11-02');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('John', 'Smith', '1964-02-28');